# Generated by Django 5.1.5 on 2025-02-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("admin", "Admin"), ("customer", "Customer")],
                default="customer",
                max_length=10,
                verbose_name="User type",
            ),
        ),
    ]
