# Generated by Django 5.1.5 on 2025-02-25 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_customuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(
                blank=True,
                help_text="Please indicate your age (optional)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        18, message="Age cannot be less than 2 years old"
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Age cannot be more than 100 years old"
                    ),
                ],
                verbose_name="age",
            ),
        ),
    ]
